name: iOS - Build

on:
  push:
    branches: [ "SIANXSVC-1225" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-13
    env:
      PROJECT_NAME: AnexiaAutheticator
      SCHEME: AnexiaAuthenticator
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with: 
          xcode-version: '15.2'
      - name: Clean
        run: |
          xcodebuild clean -project ./TwoFas/${{env.PROJECT_NAME}}.xcodeproj -scheme ${{env.SCHEME}} -destination 'generic/platform=iOS'
      - name: Testing App
        run: |
          xcodebuild test -project ./TwoFas/${{env.PROJECT_NAME}}.xcodeproj -scheme ${{env.SCHEME}} -destination platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro Max | xcpretty
      - name: Build
        run: |
          xcodebuild build-for-testing -project ./TwoFas/${{env.PROJECT_NAME}}.xcodeproj -scheme ${{env.SCHEME}} -sdk iphonesimulator
      - name: Run Tests
        run: |
          xcodebuild test-without-building -project ./TwoFas/${{env.PROJECT_NAME}}.xcodeproj -scheme ${{env.SCHEME}} -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro Max'
      - name: Build/Release
        uses: hectorguerrini/build-ios-action@v1.0.4

      
