name: Xcode - Build and Analyze

on:
  push:
    branches: [ "SIANXSVC-1225" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    env:
      PROJECT_NAME: AnexiaAutheticator
      SCHEME: AnexiaAutheticator
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "${{env.SCHEME}}" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
      - name: Clean
        run: |
          xcodebuild clean -project ./TwoFas/${{env.PROJECT_NAME}}.xcodeproj -scheme "${{env.SCHEME}}" -destination 'generic/platform=iOS'
      - name: Run Tests
        run: |
          xcodebuild test-without-building -scheme ${{env.SCHEME}} -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
      - name: Build/Release
        uses: hectorguerrini/build-ios-action@v1.0.4

      
