name: Xcode - Build and Analyze

on:
  push:
    branches: [ "SIANXSVC-1225" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        working-directory: ./TwoFas
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Test without Building iOS Application   
        uses: UmutSERIFLER/test-ios-application@1.0.4
        with:
          projectName: AnexiaAutheticator
      - name: Build
        uses: yukiarrr/ios-build-action@v1.11.2
      - name: Build/Release Action
        uses: hectorguerrini/build-ios-action@v1.0.4
      
